In [3]:
import pandas as pd

In [5]:
# Series
price = pd.Series([700, 500, 870])
print(price)
print(type(price))

0    700
1    500
2    870
dtype: int64
<class 'pandas.Series'>

In [6]:
print(price.values)

[700 500 870]

In [7]:
print(price.index)

RangeIndex(start=0, stop=3, step=1)

In [10]:
price = pd.Series([700, 500, 870], index=['HP', 'Lenovo', 'Asus'])
print(price)
print(type(price))

HP        700
Lenovo    500
Asus      870
dtype: int64
<class 'pandas.Series'>

In [12]:
print(price.values)
print(price.index)

[700 500 870]
Index(['HP', 'Lenovo', 'Asus'], dtype='str')

In [18]:
#DataFrame
laptops = pd.DataFrame({
    "Company": ['HP', 'Lenovo', 'Asus'],
    "Price": [700, 500, 870],
})

In [20]:
print(laptops)

  Company  Price
0      HP    700
1  Lenovo    500
2    Asus    870

In [19]:
print(laptops.columns)
print(laptops.index)

Index(['Company', 'Price'], dtype='str')
RangeIndex(start=0, stop=3, step=1)

In [23]:
price = pd.Series([700, 500, 870], index=['HP', 'MSI', 'Asus'])
print(price)
print(type(price))

HP      700
MSI     500
Asus    870
dtype: int64
<class 'pandas.Series'>

In [26]:
df = pd.read_csv('laptop.csv', encoding='windows-1251')
print(df.head())
print(type(df))

   laptop_ID Company      Product   TypeName  Inches  \
0          1   Apple  MacBook Pro  Ultrabook    13.3
1          2   Apple  Macbook Air  Ultrabook    13.3
2          3      HP       250 G6   Notebook    15.6
3          4   Apple  MacBook Pro  Ultrabook    15.4
4          5   Apple  MacBook Pro  Ultrabook    13.3

                     ScreenResolution                         Cpu   Ram  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB
1                            1440x900        Intel Core i5 1.8GHz   8GB
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB

                Memory                           Gpu  OpSys  Weight  \
0            128GB SSD  Intel Iris Plus Graphics 640  macOS  1.37kg
1  128GB Flash Storage        Intel HD Graphics 6000  macOS  1.34kg
2            256GB SSD         Intel HD Graphics 620  No OS  1.86kg
3            512GB SSD            AMD Radeon Pro 455  macOS  1.83kg
4            256GB SSD  Intel Iris Plus Graphics 650  macOS  1.37kg

   Price_euros
0      1339.69
1       898.94
2       575.00
3      2537.45
4      1803.60
<class 'pandas.DataFrame'>

In [29]:
print(df.head(2))

   laptop_ID Company      Product   TypeName  Inches  \
0          1   Apple  MacBook Pro  Ultrabook    13.3
1          2   Apple  Macbook Air  Ultrabook    13.3

                     ScreenResolution                   Cpu  Ram  \
0  IPS Panel Retina Display 2560x1600  Intel Core i5 2.3GHz  8GB
1                            1440x900  Intel Core i5 1.8GHz  8GB

                Memory                           Gpu  OpSys  Weight  \
0            128GB SSD  Intel Iris Plus Graphics 640  macOS  1.37kg
1  128GB Flash Storage        Intel HD Graphics 6000  macOS  1.34kg

   Price_euros
0      1339.69
1       898.94

In [31]:
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(1303, 13)
1303
13

In [32]:
print(df.tail())

      laptop_ID Company                              Product  \
1298       1316  Lenovo                       Yoga 500-14ISK
1299       1317  Lenovo                       Yoga 900-13ISK
1300       1318  Lenovo                   IdeaPad 100S-14IBR
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)

                TypeName  Inches                            ScreenResolution  \
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300            Notebook    14.0                                    1366x768
1301            Notebook    15.6                                    1366x768
1302            Notebook    15.6                                    1366x768

                                       Cpu   Ram              Memory  \
1298            Intel Core i7 6500U 2.5GHz   4GB           128GB SSD
1299            Intel Core i7 6500U 2.5GHz  16GB           512GB SSD
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB  64GB Flash Storage
1301            Intel Core i7 6500U 2.5GHz   6GB             1TB HDD
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB           500GB HDD

                        Gpu       OpSys  Weight  Price_euros
1298  Intel HD Graphics 520  Windows 10   1.8kg        638.0
1299  Intel HD Graphics 520  Windows 10   1.3kg       1499.0
1300      Intel HD Graphics  Windows 10   1.5kg        229.0
1301     AMD Radeon R5 M330  Windows 10  2.19kg        764.0
1302      Intel HD Graphics  Windows 10   2.2kg        369.0

In [33]:
print(df.tail(3))

      laptop_ID Company                              Product  TypeName  \
1300       1318  Lenovo                   IdeaPad 100S-14IBR  Notebook
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon  Notebook
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)  Notebook

      Inches ScreenResolution                                   Cpu  Ram  \
1300    14.0         1366x768  Intel Celeron Dual Core N3050 1.6GHz  2GB
1301    15.6         1366x768            Intel Core i7 6500U 2.5GHz  6GB
1302    15.6         1366x768  Intel Celeron Dual Core N3050 1.6GHz  4GB

                  Memory                 Gpu       OpSys  Weight  Price_euros
1300  64GB Flash Storage   Intel HD Graphics  Windows 10   1.5kg        229.0
1301             1TB HDD  AMD Radeon R5 M330  Windows 10  2.19kg        764.0
1302           500GB HDD   Intel HD Graphics  Windows 10   2.2kg        369.0

In [44]:
print(df.sample(2, random_state=42))

      laptop_ID  Company            Product  TypeName  Inches  \
479         486  Toshiba  Portege X30-D-10J  Notebook    13.3
1022       1036       HP  Spectre 13-V100nv  Notebook    13.3

                 ScreenResolution                         Cpu  Ram     Memory  \
479   IPS Panel Full HD 1920x1080  Intel Core i5 7200U 2.5GHz  8GB  256GB SSD
1022  IPS Panel Full HD 1920x1080  Intel Core i5 7200U 2.5GHz  8GB  256GB SSD

                        Gpu       OpSys  Weight  Price_euros
479   Intel HD Graphics 620  Windows 10  1.05kg       1672.0
1022  Intel HD Graphics 620  Windows 10  1.11kg       1149.0

In [45]:
print(df.columns)

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='str')

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Memory            1303 non-null   str
 9   Gpu               1303 non-null   str
 10  OpSys             1303 non-null   str
 11  Weight            1303 non-null   str
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(10)
memory usage: 132.5 KB

In [47]:
print(df.dtypes)

laptop_ID             int64
Company                 str
Product                 str
TypeName                str
Inches              float64
ScreenResolution        str
Cpu                     str
Ram                     str
Memory                  str
Gpu                     str
OpSys                   str
Weight                  str
Price_euros         float64
dtype: object

In [48]:
df.tail(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.0
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.0

In [49]:
df.describe()

         laptop_ID       Inches  Price_euros
count  1303.000000  1303.000000  1303.000000
mean    660.155794    15.017191  1123.686992
std     381.172104     1.426304   699.009043
min       1.000000    10.100000   174.000000
25%     331.500000    14.000000   599.000000
50%     659.000000    15.600000   977.000000
75%     990.500000    15.600000  1487.880000
max    1320.000000    18.400000  6099.000000

In [54]:
df.describe(include="str")

,Company,Product,TypeName,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
count,1303,1303,1303,1303,1303,1303,1303,1303,1303,1303
unique,19,618,6,40,118,9,39,110,9,179
top,Dell,XPS 13,Notebook,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.2kg
freq,297,30,727,507,190,619,412,281,1072,121

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
df.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

In [60]:
df["Company"].head(10)

0    Apple
1    Apple
2       HP
3    Apple
4    Apple
5     Acer
6    Apple
7    Apple
8     Asus
9     Acer
Name: Company, dtype: str

In [61]:
df["Company"]

0        Apple
1        Apple
2           HP
3        Apple
4        Apple
         ...
1298    Lenovo
1299    Lenovo
1300    Lenovo
1301        HP
1302      Asus
Name: Company, Length: 1303, dtype: str

In [62]:
df[["Company", "laptop_ID", "Price_euros" ]].head(10)

  Company  laptop_ID  Price_euros
0   Apple          1      1339.69
1   Apple          2       898.94
2      HP          3       575.00
3   Apple          4      2537.45
4   Apple          5      1803.60
5    Acer          6       400.00
6   Apple          7      2139.97
7   Apple          8      1158.70
8    Asus          9      1495.00
9    Acer         10       770.00

In [63]:
df.loc[0]

laptop_ID                                            1
Company                                          Apple
Product                                    MacBook Pro
TypeName                                     Ultrabook
Inches                                            13.3
ScreenResolution    IPS Panel Retina Display 2560x1600
Cpu                               Intel Core i5 2.3GHz
Ram                                                8GB
Memory                                       128GB SSD
Gpu                       Intel Iris Plus Graphics 640
OpSys                                            macOS
Weight                                          1.37kg
Price_euros                                    1339.69
Name: 0, dtype: object

In [64]:
df.iloc[0]

laptop_ID                                            1
Company                                          Apple
Product                                    MacBook Pro
TypeName                                     Ultrabook
Inches                                            13.3
ScreenResolution    IPS Panel Retina Display 2560x1600
Cpu                               Intel Core i5 2.3GHz
Ram                                                8GB
Memory                                       128GB SSD
Gpu                       Intel Iris Plus Graphics 640
OpSys                                            macOS
Weight                                          1.37kg
Price_euros                                    1339.69
Name: 0, dtype: object

In [65]:
df.loc[2, "Company"]

'HP'

In [70]:
df.iloc[2, 3]

'Notebook'

In [69]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [71]:
df.iloc[0:3]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

In [73]:
df.loc[0:3]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45

In [74]:
df.iloc[15]

laptop_ID                                           16
Company                                          Apple
Product                                    MacBook Pro
TypeName                                     Ultrabook
Inches                                            13.3
ScreenResolution    IPS Panel Retina Display 2560x1600
Cpu                               Intel Core i5 2.3GHz
Ram                                                8GB
Memory                                       256GB SSD
Gpu                       Intel Iris Plus Graphics 640
OpSys                                            macOS
Weight                                          1.37kg
Price_euros                                    1518.55
Name: 15, dtype: object

In [75]:
# Маски
my_mask = df["Price_euros"] < 1000
my_mask.head()

0    False
1     True
2     True
3    False
4    False
Name: Price_euros, dtype: bool

In [76]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [77]:
type(my_mask)

pandas.Series

In [79]:
cheap_laptops = df[my_mask]
cheap_laptops.head(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
5,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00
9,10,Acer,Swift 3,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.6kg,770.00
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.90
11,12,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,500GB HDD,Intel HD Graphics 520,No OS,1.86kg,344.99
13,14,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,498.90
16,17,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,745.00
18,19,Lenovo,IdeaPad 320-15IKB,Notebook,15.6,Full HD 1920x1080,Intel Core i3 7100U 2.4GHz,8GB,1TB HDD,Nvidia GeForce 940MX,No OS,2.2kg,499.00
19,20,Dell,XPS 13,Ultrabook,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,128GB SSD,Intel UHD Graphics 620,Windows 10,1.22kg,979.00

In [83]:
apple_mask = df["Company"] == "Apple"
cheap_apple = df[apple_mask & my_mask]
cheap_apple.head(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
7,8,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,1158.70
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
14,15,Apple,"MacBook 12""",Ultrabook,12.0,IPS Panel Retina Display 2304x1440,Intel Core M m3 1.2GHz,8GB,256GB SSD,Intel HD Graphics 615,macOS,0.92kg,1262.40
15,16,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1518.55
17,18,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00

In [85]:
apple_mask = df["Company"] == "Apple"
cheap_apple = df[apple_mask | my_mask]
cheap_apple[["Company", "laptop_ID", "Price_euros" ]].head(10)

   Company  laptop_ID  Price_euros
0    Apple          1      1339.69
1    Apple          2       898.94
2       HP          3       575.00
3    Apple          4      2537.45
4    Apple          5      1803.60
5     Acer          6       400.00
6    Apple          7      2139.97
7    Apple          8      1158.70
9     Acer         10       770.00
10      HP         11       393.90

In [86]:
apple_mask = df["Company"] == "Apple"
cheap_apple = df[~ apple_mask ]
cheap_apple[["Company", "laptop_ID", "Price_euros" ]].head(10)

   Company  laptop_ID  Price_euros
2       HP          3       575.00
5     Acer          6       400.00
8     Asus          9      1495.00
9     Acer         10       770.00
10      HP         11       393.90
11      HP         12       344.99
13    Dell         14       498.90
16    Dell         17       745.00
18  Lenovo         19       499.00
19    Dell         20       979.00

In [94]:
light_df = df[(df["Weight"] == "1.37kg") & (df["Price_euros"] > 1800)]
light_df.head(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.6
249,254,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,512GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,2040.0
253,258,Lenovo,Yoga 920-13IKB,2 in 1 Convertible,13.9,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,512GB SSD,Intel UHD Graphics 620,Windows 10,1.37kg,1849.0
270,275,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.9GHz,8GB,512GB SSD,Intel Iris Graphics 550,macOS,1.37kg,1958.9
596,603,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,2025.0
792,801,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,1970.0
867,878,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,1950.0
924,938,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,1825.0

In [95]:
light_df.iloc[0]

laptop_ID                                            5
Company                                          Apple
Product                                    MacBook Pro
TypeName                                     Ultrabook
Inches                                            13.3
ScreenResolution    IPS Panel Retina Display 2560x1600
Cpu                               Intel Core i5 3.1GHz
Ram                                                8GB
Memory                                       256GB SSD
Gpu                       Intel Iris Plus Graphics 650
OpSys                                            macOS
Weight                                          1.37kg
Price_euros                                     1803.6
Name: 4, dtype: object

In [96]:
light_df.loc[0]

KeyError: 0

In [97]:
light_df_reset = light_df.reset_index(drop=True)
light_df_reset.head(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.6
1,254,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,512GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,2040.0
2,258,Lenovo,Yoga 920-13IKB,2 in 1 Convertible,13.9,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,512GB SSD,Intel UHD Graphics 620,Windows 10,1.37kg,1849.0
3,275,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.9GHz,8GB,512GB SSD,Intel Iris Graphics 550,macOS,1.37kg,1958.9
4,603,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,2025.0
5,801,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,1970.0
6,878,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,1950.0
7,938,Lenovo,ThinkPad Yoga,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.37kg,1825.0

In [98]:
price_view = df[["laptop_ID", "Company", "Product", "Price_euros" ]]
price_view.head(10)

   laptop_ID Company          Product  Price_euros
0          1   Apple      MacBook Pro      1339.69
1          2   Apple      Macbook Air       898.94
2          3      HP           250 G6       575.00
3          4   Apple      MacBook Pro      2537.45
4          5   Apple      MacBook Pro      1803.60
5          6    Acer         Aspire 3       400.00
6          7   Apple      MacBook Pro      2139.97
7          8   Apple      Macbook Air      1158.70
8          9    Asus  ZenBook UX430UN      1495.00
9         10    Acer          Swift 3       770.00

In [101]:
price_view.sort_values("Price_euros", ascending=False)

      laptop_ID Company                               Product  Price_euros
196         200   Razer                             Blade Pro       6099.0
830         839   Razer                             Blade Pro       5499.0
610         617  Lenovo                          Thinkpad P51       4899.0
749         758      HP                              Zbook 17       4389.0
1066       1081    Asus                            ROG G701VO       3975.0
...         ...     ...                                   ...          ...
290         295    Acer                  Chromebook C910-C2ST        199.0
31           32    Asus  E402WA-GA010T (E2-6110/2GB/32GB/W10)        199.0
1120       1135    Vero      V131 (X5-Z8350/4GB/32GB/FHD/W10)        196.0
20           21    Asus                       Vivobook E200HA        191.9
1215       1233    Acer      C740-C9QX (3205U/2GB/32GB/Chrome        174.0

[1303 rows x 4 columns]

In [105]:
price_view.sort_values(["Company", "Price_euros"], ascending=[True, False])

      laptop_ID Company                           Product  Price_euros
1189       1207    Acer                   Predator G9-793      2599.00
788         797    Acer                   Predator G9-793      2299.00
730         738    Acer                       Predator 17      1935.00
679         687    Acer                   Aspire VX5-591G      1299.00
1000       1014    Acer                           Nitro 5      1260.00
...         ...     ...                               ...          ...
1120       1135    Vero  V131 (X5-Z8350/4GB/32GB/FHD/W10)       196.00
514         521  Xiaomi                       Mi Notebook      1399.95
184         188  Xiaomi                       Mi Notebook      1199.00
192         196  Xiaomi                       Mi Notebook       999.90
877         888  Xiaomi                       Mi Notebook       935.00

[1303 rows x 4 columns]

In [106]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [107]:
ram_df = df["Ram"].str.replace("GB", "")

In [108]:
ram_df.head()

0     8
1     8
2     8
3    16
4     8
Name: Ram, dtype: str

In [109]:
df["Ram_GB"] = 1

In [110]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,1
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,1

In [111]:
df["Ram_GB"] = ram_df.astype(int)

In [112]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,8
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,8
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,8
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,16
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,8

In [113]:
df["Weight_kg"] = df["Weight"].str.replace("kg", "").astype(float)

In [114]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB,Weight_kg
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,8,1.37
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,8,1.34
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,8,1.86
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,16,1.83
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,8,1.37

In [118]:
df[["Ram", "Weight", "Ram_GB", "Weight_kg"]].dtypes

Ram              str
Weight           str
Ram_GB         int64
Weight_kg    float64
dtype: object

In [119]:
def get_price_group(price):
    if price < 1000:
        return "До 1000 евро"
    return "От 1000 евро"


df["Price_group"] = df["Price_euros"].apply(get_price_group)

In [120]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB,Weight_kg,Price_group
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,8,1.37,От 1000 евро
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,8,1.34,До 1000 евро
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,8,1.86,До 1000 евро
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,16,1.83,От 1000 евро
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,8,1.37,От 1000 евро

In [121]:
df['new'] = 0

In [122]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB,Weight_kg,Price_group,new
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,8,1.37,От 1000 евро,0
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,8,1.34,До 1000 евро,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,8,1.86,До 1000 евро,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,16,1.83,От 1000 евро,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,8,1.37,От 1000 евро,0

In [123]:
df.to_csv("new_laptop.csv", encoding='utf-8', index=False)

In [124]:
df = df.drop(columns=["new"])

In [125]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB,Weight_kg,Price_group
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,8,1.37,От 1000 евро
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,8,1.34,До 1000 евро
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,8,1.86,До 1000 евро
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,16,1.83,От 1000 евро
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,8,1.37,От 1000 евро

In [126]:
df = df.drop(index=0)

In [127]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Ram_GB,Weight_kg,Price_group
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,8,1.34,До 1000 евро
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,8,1.86,До 1000 евро
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,16,1.83,От 1000 евро
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,8,1.37,От 1000 евро
5,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00,4,2.10,До 1000 евро

In [128]:
df.to_csv("new_laptop.csv", encoding='utf-8', index=False)